---
title: "MATH 3MB3 Final Project"
author: "Sofian Khan, Muhammad Khan, Stephem Zanette, Faris Abuain"
date: "2025-12-12"
output: pdf_document
---

## Introduction

A 2021 report by the Government of Canada’s Pain Task Force found that 1 in 5 Canadians live with some form of chronic pain. This includes 1 in 5 children and youth, as well as 1 in 3 adults over the age of 65 [reference 1](https://www.canada.ca/en/health-canada/corporate/about-health-canada/public-engagement/external-advisory-bodies/canadian-pain-task-force/report-2021.html). Chronic pain often results in a significantly lower quality of life, including (but not limited to) poor sleep, impacted ability to socialize, and inability to work. In addition to chronic pain, acute pain (defined as pain requiring immediate medical attention) is a common occurence in Canada, accounting for 78% of all emergency department visits [reference 2](https://ououd.casn.ca/modules/module-7/topic-7a.html). As a result, the treatment strategies and methods for the management of pain is a topic of great importance for both medical professionals and policy makers in the Canadian healthcare system. 

Commonly-used medications for the treatment and management of pain include aceatominophen (Tylenol®), non-steroidal antinflamatory drugs (NSAIDs), topical medications (lidocaine, capsaicin, etc.) and opioids [reference 3](https://my.clevelandclinic.org/health/treatments/21514-pain-management). However, in this report, we will focus on two specific forms of drug-delivery: intravenous (IV) administration, and extended-release pills. IV administration involves the infusion of a drug directly into the veins of the patient, and is often completed under medical supervision, in either a hospital or home care setting. In addition to IV administration of opiates such as morphine and fentanyl, commonly used for severe pain in hospitalized patients, non-opiate drugs such as lidocaine, ketamine, and phentolamine have been used for the management of patients with pain stemming from chronic conditions [reference 4](https://pubmed.ncbi.nlm.nih.gov/23703410/). 

Extended-release pills have also shown significant promise for the treatment of chronic pain, overcoming previous limitations of pill-delivery to patients with acute pain only. For example, extended-release opiates are generally preferred for patients with chronic pain as they reduce interruptions of sleep, increase compliance, and offer less reinforcement for drug missuse (a significant concern for opiates) [reference 5](https://pmc.ncbi.nlm.nih.gov/articles/PMC3004644/). Additionally, extended-release formulations of over-the-counter (OTC) pain medications offer similar benefits to patients with lower-grade chronic pain, and are generally effective and well-tolerated for long-term use [reference 6](https://www.sciencedirect.com/science/article/pii/S1063458406002950).

Recent reviews of the medical literature on the safety and efficacy of long-acting/extended-release opioids for chronic pain have suggested that much of the current body of research is of poor quality and limited scope [reference 7](https://pubmed.ncbi.nlm.nih.gov/24115561/),[reference 8](https://www.ohsu.edu/sites/default/files/2019-01/Opioids_final_report_update-6_Jul_11.pdf). In particular, these reviews emphasize the lack of sufficient statistical evidence to make determinations as to comparative safety and efficacy between classes of extended-release drugs. The literature on the safety and efficacy of IV administration is also lacking, with inconclusive results on the safety and efficacy of intravenous administration of pain medications for chronic pain management [reference 9](https://pubmed.ncbi.nlm.nih.gov/29395284/). Some studies have found that IV administration of ibuprofen (an NSAID) to be effective and well-tolerated in older patients and have suggested IV administration of acetaminophen as a safer alternative to opioids [reference 10](https://www.sciencedirect.com/science/article/pii/S014929182500164X),[reference 11](https://canjhealthtechnol.ca/index.php/cjht/article/view/RC1508/1587).  

The goal of this report is to investigate the dynamics of drug absorption and metabolism for different methods of drug delivery, through a combination of mathematical modelling and numerical simulation. In particular, we will perform a full mathematical analysis of drug dynamics in the body in order to explore the implications for the safety and efficacy of common pain management strategies. The question we seek to investigate is whether extended-release pills or IV administration is a more effective strategy for patients with chronic and/or acute pain, as well as the relative safety of each strategy given patient metabolism and tolerance.
